### ISSUE TITLE
Incorrect previous value when listening nested `deepMap`

### ISSUE THREAD

**Issue by euaaaio** [nanostores/nanostores#288]
We had a bug with an incorrect previous value passed from `onNotify` when listening nested `deepMap`. I fixed this by spread cloning of the old value. But we still have a bug when we have more than one level of nesting.

**Simple test**

```ts
test('notifies correct previous value from deep store', () => {
  type DeepValue = { a: number; b: { nested: { deep: number } } }

  let events: DeepValue[] = []
  let $store = deepMap<DeepValue>({
    a: 0,
    b: {
      nested: {
        deep: 0
      }
    }
  })

  let unbind = onNotify($store, ({ oldValue }) => {
    events.push(oldValue)
  })

  $store.setKey('a', 1)
  $store.setKey('b.nested.deep', 1)
  $store.setKey('b.nested.deep', 2)
  deepStrictEqual(events, [
    { a: 0, b: { nested: { deep: 0 } } },
    { a: 1, b: { nested: { deep: 0 } } },
    { a: 1, b: { nested: { deep: 1 } } }
  ])
  unbind()
})
```

For now, we can use `structuredClone` to clone and pass the correct old value. But I remember, that we wanted to do it differently to improve performance. 

@dkzlv, what do you think is the best way to do it?

**Comment by dkzlv** [comment]
@euaaaio That's a tricky question!

I think, we're no Redux in a sense that we do not promote/position ourself as an immutable state manager. We're fine with mutation, and even kinda encouraging it with internal talks of opening `notify` as part of the public API.

So indeed, if we want to have `oldValue`, we need to use something like `structuredClone`. The only thing is that it needs to be in the core, specifically in `onNotify` hook — that's the only place where `oldValue` is part of the public API, if I understand correctly. I don't see any other way of doing it, tbh. 

I'm fine with using `structuredClone`. It won't harm the performance (it's very fast; besides, Redux clones every single goddamn thing on each change, and it doesn't seem to hurt performance that much!).

The only 2 concern I have are:

1. browser support. But since it's scoped to a limited feature, I think I'd be fine with having it there. We just need a disclaimer in the doc that onNotify will use `structuredClone` [with a link](https://caniuse.com/mdn-api_structuredclone);
2. again, we're no Redux, we do not enforce devs to only store serializable stuff in there. For all we know it can be something not [transferable](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects), like a function (completely plausible, btw), a class or something else. I think, we can wrap the `structuredClone` call with a `try..catch` and, again, add a disclaimer to README that using `onNotify` forces you to have transferable stuff in stores.

I can implement this if everybody's on board.

cc @ai
