### ISSUE TITLE
TypeScript error with `map.setKey` when passing `undefined` to un-set a key

### ISSUE THREAD

**Issue by psychedelicious** [nanostores/nanostores#308]
To un-set a `map`'s key, we pass `undefined` to the `setKey` method:

```js
const $store = map({});
$store.setKey('some_key', undefined) // OK
```

When using TypeScript, this errors when the value itself is not typed as `SomeType | undefined`:

```ts
const $store = map<Record<string, string>>({});
$store.setKey('some_key', undefined) // Argument of type 'undefined' is not assignable to parameter of type 'string'.ts(2345)
```

**Comment by gismya** [comment]
I'd argue it's up to the implementing developer to do this, rather than the package. It's annoying for Record generics, but that's the case anytime you're using that (Outside of nanostores as well). `Record<string, string | undefined>` is closer to the truth for any generic record than `Record<string, string>`. Conversely, the PR would allow us to unset values in maps that always should have values, and I think that's worse.

We're using both kinds in our project, and when we need to unset Record generics we use non-null assertions like this `setKey(key, undefined!)`.

**Comment by psychedelicious** [comment]
Thanks for the feedback @gismya. You're right that `Record<string, string | undefined>` works fine for most situations. I'm happy for this to be closed as nofix with your suggestions as solutions. It's good to remember that sometimes we know more than TS and don't need to bow to its every whim.

I'd prefer an explicit `removeKey(key)` over more-or-less using `undefined` as a sentinel value, but I think that's against the minimal spirit of this library.

**Comment by ai** [comment]
We have this type check for the reason.

Imagine if you have code like:

```ts
let $store = atom<{ required: number, optional?: number }>({ required: 1, optional: 2 })
$store.setKey('required', undefined) // ← Types should prohibbit removing `required` type
```

So explicit `removeKey` anyway will not work in this case.
