### ISSUE TITLE
nanostores not compatible by default with Next.js

### ISSUE THREAD

**Issue by Saionaro** [nanostores/nanostores#33]
Generated server side code of `nextjs` fails because of requiring ES module:
https://github.com/ai/nanostores/blob/cbc3c22aa19e14d4a9cf8d54cc37c2e5ee400d85/package.json#L22
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/***/project/node_modules/nanostores/react/index.js
require() of ES modules is not supported.
require() of /Users/***/project/node_modules/nanostores/react/index.js from /Users/***/project/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/***/project/node_modules/nanostores/react/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/***/project/node_modules/nanostores/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.nanostores/react (/Users/***/project/.next/server/pages/index.js:93:18)
    at __webpack_require__ (/Users/***/project/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Component/Component.tsx:7:74)
    at Object../components/Component/Component.tsx (/Users/***/project/.next/server/pages/index.js:22:1)
    at __webpack_require__ (/Users/***/project/.next/server/webpack-runtime.js:33:42) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by ai** [comment]
In one hand, we can move Nano Stores to dual ESM/CJS package via `dual-publish`.

In other hand, Node.js community is started migration to ESM only packages.

I will think about it.

**Comment by ai** [comment]
Migration to dual ESM/CJS package will increase JS bundle from 152 to 187 (tree shaking is less effective).

Any idea how to enable ESM in Next.js SSR? (anyway, many Sindre Sorhus’ dependencies are going to ESM only too).

**Comment by ExpressGradient** [comment]
I'm also facing the same issue when using it in my library.
I think dual publish would be a great thing to do for nanostore.

**Comment by Mitsunee** [comment]
So I just banged my head against this wall for a good hour or so:
- https://github.com/martpie/next-transpile-modules/ fixes the issue with esm not yet being supported with a simple change to the nextjs config file that can be reverted easily in the future
- now the issue is nextjs serverside rendering: `localStorage is not defined` while the serverside is pre-rendering the page (I'm only a newbie when it comes to react so I have no clue about serverside stuff yet, sorry)
  - This eventually resolves itself in dev, so it *might* be fine for static apps that don't actually use SSR, but in dev it causes this error either way
- I also had to do the following code just to get debug output printed out (will probably be the same for any other values) without getting a "text content does not match" error:

```js
const [debug, setDebug] = useState(false);
const store = useStore(myStore);

useEffect(() => {
  store && setDebug(JSON.stringify(store, null, 2));
}, [store]);

return <>{debug && <pre><code>{debug}</code></pre>}</>
```

**Comment by ai** [comment]
Since ESM is a future of JS, I think we will use @Mitsunee fix (he added it to docs) https://github.com/nanostores/nanostores/pull/34

`localStorage` changes I will release in next 0.4 release (could take a week).

**Comment by gor918** [comment]
Hi, we are actively using Nanostores in our React apps, and now we are trying to use it with Next.js. I just wanted to understand if there are any short-term plans to add CJS support (I understand that it may increase the bundle size)
The problem is that we have hooks written with Nanostores, and now we are unable to use the same code in our Next.js apps :)

**Comment by ai** [comment]
> if there are any short-term plans to add CJS support

No. There are no plans.

The main reason:
1. It will reduce maintainability. I have many projects, including CJS-only, dual-CJS/ESM, and ESM-only. According to my personal experience with all these projects, dual CJS/ESM package requires more time for maintain.
2. CJS is not long-term solution. It is better to spend time to adding ESM support to Next.js.

**Comment by Mitsunee** [comment]
Next.js has no issues with using nanostores, despite being ESM-only. I don't have any special configuration anymore and it just works now and has been like that for multiple major versions now.
